######################################################
##                                                  ##
##                  SSB - OneBlock                  ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Where should the one-block be?
# That's the offset from the center of the new island.
block-offset: -0.5, -1, -0.5

# How should the timer between phases be formatted?
# This section can support multiple lines.
timer-format: '&6{0}'

# Set the hierarchy of the phases
phases:
  - 'plains-phase.json'
  - 'underground-phase.json'
  - 'snow-phase.json'
  - 'ocean-phase.json'
  - 'jungle-phase.json'
  - 'red-desert-phase.json'
  - 'nether-phase.json'
  - 'idyll-phase.json'
  - 'desolate-phase.json'
  - 'end-phase.json'

# Should /is oneblock will be injected into SuperiorSkyblock?
# This command is identical to /oneblock check.
# The permission for using the command will be superior.island.oneblock
inject-island-command: true

# List of schematics that will be used for one-block.
# If you want all schematics to work, set this list to `whitelisted-schematics: []`
whitelisted-schematics: []

# How should the module save data?
# Use 'SQL' or 'FLAT'.
# Warning: Changing this value mid-session will cause data to be lost.
data-type: FLAT

# When enabled, people that finish the last phase will be back to phase 1, starting over again.
phases-loop: false

# Whether OneBlock can be interacted with pistons.
# When true, players will be able to move the OneBlock using pistons.
piston-interaction: true

# Should destroyed blocks drop naturally above the OneBlock?
# It means items will scatter around above the OneBlock, just like normal block drops.
# When false, items will drop exactly in the center above the OneBlock, without any spread.
drop-naturally: true